### ISSUE TITLE
My new changes are not in master

### ISSUE THREAD

**Issue by BJNFNE** [DerCodeDev/VMDConverter#29]

**Comment by BJNFNE** [comment]
Currently VMDConverter can't be compiled due to the fact thats now broken... becuase my change from convertVideoMP3 to convertAudioMP3 isn't there aswell not the russian support

**Comment by DerCodeDev** [comment]
I know I made a mistake yesterday and it will be fixed today

**Comment by BJNFNE** [comment]
Perfect
